### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [glenwiley/entropypic#1]
Dear Glen, could you be so kind to generate .exe for the rest of us who are merely users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by glenwiley** [comment]
Hello. I have been traveling and have not had time to address your request.

**Comment by sergeevabc** [comment]
@glenwiley, when are you coming back?

**Comment by sergeevabc** [comment]
Six months passed.

**Comment by sergeevabc** [comment]
@glenwiley, did you get a chance to look into this more thoroughly?
